# Generated by Django 6.0.5 on 2026-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_assessment_notes_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
